### ISSUE TITLE
No indentation

### ISSUE THREAD

**Issue by millercl** [jeeger/ttl-mode#8] opened 2019-09-30 06:40 UTC
ttl-indent-line is zero. No whitespace on tab. Turtle-property term after new line after subject is not indented. Turtle-property term after new line after property and semi-colon is not indented. Indenting reloaded indentation removes said indentation. init.el is only the given cofiguration.

Reverting to upstream, https://bitbucket.org/nxg/ttl-mode corrects. Four spaces before property, object, or literal, inserted after line completion.  No indenting to second level of indent.

**Comment by jeeger** [comment] 2019-09-30 08:25
Hello! This looks like an installation error. If `ttl-mode.el` is loaded, `ttl-indent-line` should be a function, not zero (or is the value nil?).

**Comment by millercl** [comment] 2019-10-01 02:38
Ahoy! The indent width is like zero.
```elisp
(load "~/.emacs.d/ttl-mode") ; ✓
```
I neglected to mention, other electric punctuation works, like newline after semicolon.

```bash
git checkout 1765f3840a68ce3ef207a773003a53534f59d8d8
```
Reverting to 1765f38 corrects the issue. https://github.com/jeeger/ttl-mode/compare/1765f38...719ecea

**Comment by jeeger** [comment] 2019-10-01 06:21
You'll have to give me a turtle sample that's not indented correctly, so I can check what's wrong.

**Comment by jeeger** [comment] 2019-10-07 09:18
Without a sample to reproduce, I'll close this issue for now. Reopen if you can provide some sample ttl code (preferably a whole file) on which indentation fails.

**Closed as completed by jeeger** 2019-10-07 09:18 UTC
