### ISSUE TITLE
Problems with hashes in URIs

### ISSUE THREAD

**Issue by kjetilk** [jeeger/ttl-mode#2] opened 2019-07-07 20:53 UTC
Hi!

Great that you adopted this :-)

I have had a problem with indentation and also a bit with highlighting. We use a lot of hashes in our URIs, and I think that is what messes up the indentation in my files. 

For example, if I hit TAB at this line, it will indent the line:
https://github.com/solid/test-suite/blob/e1dc07cf0be71d856b6ec2221ee4b103a080f26a/testers/rdf-fixtures/fixture-tables/assume-world-writable.ttl#L31

If I remove the hashes from the URIs on the lines above, it indents fine, so that's why they are my prime suspects. :-) 

Also, the highlighting is also wrong. I use a different background color for comments, so I see the hash interpreted by the highlighter as a comment. 

I have looked at the elisp, but it is not my strongest language, so if you have time to check it out, it's great! :-)

**Comment by jeeger** [comment] 2019-07-08 15:02
Hello!
After some futzing around with Emacs  syntax tables and what have you, this is now fixed properly (hopefully) in commit #8483f19. Let me know if you find any other problems. Glad to see someone besides me is using this!

**Comment by kjetilk** [comment] 2019-07-08 15:23
Oh, great, thanks a lot, but I had an error when trying it out:

```
File mode specification error: (wrong-type-argument symbolp (syntax-propertize-function . ttl-propertize-comments))
Error during redisplay: (jit-lock-function 1) signaled (invalid-function (syntax-propertize-function . ttl-propertize-comments))
Error during redisplay: (jit-lock-function 581) signaled (invalid-function (syntax-propertize-function . ttl-propertize-comments))
Error during redisplay: (jit-lock-function 1085) signaled (invalid-function (syntax-propertize-function . ttl-propertize-comments))
Error during redisplay: (jit-lock-function 1660) signaled (invalid-function (syntax-propertize-function . ttl-propertize-comments))
```
It doesn't tell me anything... Does it to you?

**Comment by jeeger** [comment] 2019-07-08 16:02
Could you try restarting Emacs? Also, what version of Emacs  are you using? I can't reproduce it here.

**Comment by kjetilk** [comment] 2019-07-08 23:46
Yeah, I did restart Emacs, which is Emacs 24 (the one that is in Debian). 

I also tried to downgrade to the previous commit (bcb2a048844fea90d0bfd63db78b4294ebd4747c) and  there is no error and highlighting appears to be fixed there, but indentation appears broken, as hitting TAB pulls predicates back to column 1.

**Comment by jeeger** [comment] 2019-07-10 07:37
Ah. 'syntax-propertize-function' does seem to be supported in Emacs 24, so that can't be the problem.

In https://github.com/jeeger/ttl-mode/commit/bcb2a048844fea90d0bfd63db78b4294ebd4747c, fontification works, but `syntax-ppss` gets very confused, because it interprets parentheses in comments, throwing off indentation.

What's the value of `syntax-propertize-function` in a `ttl-mode` buffer? Could you try turning on `jit-lock-debug-mode` and `(toggle-debug-on-error)` and provide the output? How did you install `ttl-mode`?

I'm currently at a loss as to what's causing this, and I'm running `ttl-mode` here as well.

**Comment by kjetilk** [comment] 2019-07-30 14:15
Sorry for the ping times, I've been on holidays.

> What's the value of `syntax-propertize-function` in a `ttl-mode` buffer?

`nil` it seems.

`describe-variable` also says:

```
 This variable may be risky if used as a file-local variable.
```

> Could you try turning on `jit-lock-debug-mode` and `(toggle-debug-on-error)` and provide the output? 

Yeah, it seems I successfully enabled the debug mode, but I don't know where the output goes, or how I provoke it... I tried to indent here and there, and look in ` * Messages * ` but I can't see anything there. Where should the output go?

> How did you install `ttl-mode`?

Long story... :-) I have a site load path that I put stuff into, so I just checked it out in `/site/share/emacs/site-lisp/ttl-mode` and then 
```elisp
(autoload 'ttl-mode "ttl-mode" "Major mode for OWL or Turtle files" t)
```

**Comment by jeeger** [comment] 2019-07-30 14:31
No problem, I hope you enjoyed them!

> nil it seems.

That's not good. It should be `ttl-propertize-comments`.

> Yeah, it seems I successfully enabled the debug mode, but I don't know where the output goes, or how I provoke it...

`jit-lock-debug-mode` just moves some functionality into a timer, so `debug-on-error` should produce a backtrace. If you still only get errors in the previous comment, this means that the erroneous code is still inside the "undebuggable" part.

> Long story... :-) 

Could you try a `(require 'ttl-mode)`?

**Comment by jeeger** [comment] 2019-07-30 14:34
Ah, also: Did you byte-compile ttl-mode.el?

**Comment by kjetilk** [comment] 2019-07-30 14:54
> Ah, also: Did you byte-compile ttl-mode.el?

No, should I?

**Comment by jeeger** [comment] 2019-07-30 15:07
No, it could've been possible that the `.elc` file was outdated.

**Comment by kjetilk** [comment] 2019-07-30 15:07
OK, one thing, I had forgotten that I detached HEAD at bcb2a04, but now I'm at HEAD, still the variable was `nil`. I added the `require` to the startup file.  And I'm getting some debug output

```
Debugger entered--Lisp error: (invalid-function (syntax-propertize-function . ttl-propertize-comments))
  (syntax-propertize-function . ttl-propertize-comments)()
\310H\211A\300\242\302\242Z\\\241\266\311\302\242\300\242\312\211\301%\207\302\242\204\214\301\203\214\304\313\301!\206P\307\301\314H\211A\300\242\304\242Z\\\241\266\303\311\304\242\300\242\"\240\210\202E\312e\312\203\254\300\242\211@@\262W\203\254\262A\262\202\222\203\301\211@@\262\262\303\211@A\262\240\210204\322\204\322\315\316\317\320\211$\210\302\242\203\336\302\242W\203\350\2\321H\211A\300\242\302\242Z\\\241\266\302\242\262\301\262\204 \322\323!\203 \203 \324\325!\210\203a\300\242b\210 \210`V\203a`\30\331H\211A\300\242Z\\\241\266\300\242Z▒\307_V\203\350\303\311\211\300\242\\\307\245\211\262\312\211\303\242%\240\210\303\242B\203\336\211AB\241\266\202\344\211210\202\253\303\311\300\242\312\211\303\242%\240\210\300\242\303\242B\203\211@@\262\300\242Z▒V\203▒\211AB\241\266\202B\240\210\202B2034211@@\262\300\242Z▒V\203=\211202B240\210\210\266\300\242\303\242B\303\242\207" [(565) nil (nil) (nil) (1) syntax-ppss-stats 5 2 0 parse-partial-sexp nil syntax-ppss-toplevel-pos 1 add-hook before-change-functions syntax-ppss-flush-cache t 4 boundp font-lock-beginning-of-syntax-function make-local-variable syntax-begin-function get-text-property face (font-lock-string-face font-lock-doc-face font-lock-comment-face) 3 syntax-ppss-max-span syntax-ppss-cache syntax-ppss-last] 12 "\n\n(fn)"]()
\310H\211A\300\242\302\242Z\\\241\266\311\302\242\300\242\312\211\301%\207\302\242\204\214\301\203\214\304\313\301!\206P\307\301\314H\211A\300\242\304\242Z\\\241\266\303\311\304\242\300\242\"\240\210\202E\312e\312\203\254\300\242\211@@\262W\203\254\262A\262\202\222\203\301\211@@\262\262\303\211@A\262\240\210204\322\204\322\315\316\317\320\211$\210\302\242\203\336\302\242W\203\350\2\321H\211A\300\242\302\242Z\\\241\266\302\242\262\301\262\204 \322\323!\203 \203 \324\325!\210\203a\300\242b\210 \210`V\203a`\30\331H\211A\300\242Z\\\241\266\300\242Z▒\307_V\203\350\303\311\211\300\242\\\307\245\211\262\312\211\303\242%\240\210\303\242B\203\336\211AB\241\266\202\344\211210\202\253\303\311\300\242\312\211\303\242%\240\210\300\242\303\242B\203\211@@\262\300\242Z▒V\203▒\211AB\241\266\202B\240\210\202B2034211@@\262\300\242Z▒V\203=\211202B240\210\210\266\300\242\303\242B\303\242\207" [(565) nil (nil) (nil) (1) syntax-ppss-stats 5 2 0 parse-partial-sexp nil syntax-ppss-toplevel-pos 1 add-hook before-change-functions syntax-ppss-flush-cache t 4 boundp font-lock-beginning-of-syntax-function make-local-variable syntax-begin-function get-text-property face (font-lock-string-face font-lock-doc-face font-lock-comment-face) 3 syntax-ppss-max-span syntax-ppss-cache syntax-ppss-last] 12 "\n\n(fn)"])
  syntax-ppss(565)
  font-lock-fontify-syntactically-region(565 694 nil)
  font-lock-default-fontify-region(565 694 nil)
  font-lock-fontify-region(565 694)
  run-hook-with-args(font-lock-fontify-region 565 694)
  #[0 "\302\303\300\242\301\242#\207" [(565) (694) run-hook-with-args jit-lock-functions] 4 "\n\n(fn)"]()
  funcall(#[0 "\302\303\300\242\301\242#\207" [(565) (694) run-hook-with-args jit-lock-functions] 4 "\n\n(fn)"])
  jit-lock-fontify-now(565 632)
  jit-lock--debug-fontify()
  apply(jit-lock--debug-fontify nil)
  byte-code("r\30\302\303H\"\210)\301\207" [timer apply 5 6] 4)
  timer-event-handler([t 0 0 0 t jit-lock--debug-fontify nil idle 0])

```

**Comment by jeeger** [comment] 2019-07-30 16:03
Try the newest version to see whether this fixed it. Might have been caused by using quasiquoting incorrectly.

**Comment by kjetilk** [comment] 2019-07-30 23:15
It highlights correctly, but it doesn't indent, I get the following errors:

```
Error during redisplay: (jit-lock-function 1080) signaled (void-variable whitespace-trailing)
Error during redisplay: (jit-lock-function 1607) signaled (void-variable whitespace-trailing)
Error during redisplay: (jit-lock-function 691) signaled (void-variable whitespace-trailing)
Error during redisplay: (jit-lock-function 1196) signaled (void-variable whitespace-trailing)
Error during redisplay: (jit-lock-function 1706) signaled (void-variable whitespace-trailing)
Error during redisplay: (jit-lock-function 948) signaled (void-variable whitespace-trailing)
Error during redisplay: (jit-lock-function 1507) signaled (void-variable whitespace-trailing)
Error during redisplay: (jit-lock-function 1036) signaled (void-variable whitespace-trailing)
Error during redisplay: (jit-lock-function 1563) signaled (void-variable whitespace-trailing)
```

**Comment by jeeger** [comment] 2019-07-31 08:02
Very nice, we're getting somewhere. I've pushed a possible fix for this (although I don't know where the error comes from).

**Comment by kjetilk** [comment] 2019-07-31 11:33
Yeah, getting somewhere, thanks a lot! Not quite there yet. I'm not getting any errors now, but indentation doesn't work (i.e. it pulls the predicate to col 0). But I do get this.

```
syntax-propertize-function's value is ttl-propertize-comments
Local in buffer acl-test.ttl; global value is nil

  This variable may be risky if used as a file-local variable.
```
Seems like an improvement, but could it be something with the final warning message there? 

I'm not getting any debug info after enabling debug on error now.

**Comment by jeeger** [comment] 2019-07-31 12:16
Do you have a link to where the indentation fails, or a screenshot? I've indented the file linked above (`assume-world-writable.ttl`), and it indents perfectly (to my tastes☺).

> Seems like an improvement, but could it be something with the final warning message there?

The "variable may be risky" warning is about setting it via file-local variables, because an attacker might be able to execute arbitrary code using this variable. It's only relevant for file-local variables.

**Comment by kjetilk** [comment] 2019-07-31 13:17
Here's a screenshot:

![](http://dev.kjernsmo.net/tmp/Screenshot_20190731_151441.png)

**Comment by jeeger** [comment] 2019-07-31 13:44
Strange, I have absolutely no idea where that could come from. Did you reindent the whole buffer (C-x h, M-S-\)? Indentation happens line-by-line, so if you only indent one line, that's not going to work unless the previous line is already indented.

**Comment by kjetilk** [comment] 2019-07-31 13:57
No, I indendenten line-by-line with `TAB`... Could it be some tabbing setting I have that messes up?

**Comment by jeeger** [comment] 2019-07-31 13:59
You can check with `C-h k TAB` to see what Tab is bound to. It should be set to `tab-indent-for-current-line`.

**Comment by kjetilk** [comment] 2019-07-31 14:00
Oh, it says:
```
TAB (translated from <tab>) runs the command indent-for-tab-command,
which is an interactive compiled Lisp function.

It is bound to TAB.
```

Is that wrong?

**Comment by jeeger** [comment] 2019-07-31 14:03
Uh, no, I mistyped there. 

I'm all out of ideas, and installing emacs 24 currently doesn't seem too tempting. 
I suggest you try to install a newer version of Emacs if you're interested in using this mode, as I strongly suspect that's where the problems/errors are coming from.

I'll close this for now, let me know if you find out something new.

**Closed as completed by jeeger** 2019-07-31 14:03 UTC

**Comment by kjetilk** [comment] 2019-07-31 14:31
Yeah, I can see that. I actually have plans to upgrade all my boxes to the most recent Debian soon, so I can test when I get there! :-) Thanks anyway

**Comment by jeeger** [comment] 2019-07-31 14:31
Cool! I'll be thankful for any feedback!

**Comment by kjetilk** [comment] 2019-07-31 15:34
Oh, actually, I just came to think about the fact that I had already upgraded a test box, and there it does seem to work! :-)
